linters:
  enable-all: true
  disable:
    - dupl # phil: raises false positives for non-duplicate code
    - gochecknoglobals
    - gochecknoinits
    - interfacer # author says it's deprecated, gives very subjective advice
    - prealloc
linters-settings:
  goconst:
    min-len: 5
  maligned:
    suggest-new: true
issues:
  new-from-rev: 61cc8815bf172110171836581439d1822c161b42
