language: python
sudo: required

# Run on Linux and OS X:
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      language: generic

# Cache gcloud SDK across runs; this requires master to have builds:
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Environment variables:
env:
  global:
    - PROJECT_NAME=datawireio
    - CLUSTER_NAME=telepresence-testing
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    # DOCKER_PASSWORD:
    - secure: "TJCb6M9p8nTWuBDm2JvPaBAnH6nZAC7MIEL5qaZTno3W7VA9hkMke/eOIXCNVT8B6OKTM60B1PlqZ+QXnlSUECn0pNEU5DXJGcOktJuUc9KPsCIMVPpmpdElkULREGnOtJqyVH8GAlLTT98uXbdRlopyvmaa/NEw3W0QtmRsCnfJ9UlzH9lOiJ3eLMohNAJTCZKEhfEHY2Wt59wMXYt8bshKzo0wqfbKBjgFUQW4ixrG/ypwTm2qS8qsojfCwmXeCyaNdZxWIZ7tFPWXGzLjjBmqOOlpGueYjVoj8yu3rW8hcJDjwxAAxe05PLdh8Ea6LrKDijYf+5eQaQcd/yhCFgOJDMDHjLKIr8mBKe0BhoLeGa9o9H2d0WrzeKO7PdqMbMq4eNM7MswxcmUy26wlSnvzhRu8NVnYnSn8PKJuHdtxtgNWQTE2nvBJYtbuG9qMd5ihdIesJrIs7aXfyCx2RshZ4PhSA9EvHhzsuSS/d2RPZn2O3vUSuMFlkJV2Ox5VCEgBHxnXKHdmj9/t4rvwwY3EQwgRAFE81nSEuuWuhcz/q2EWjh9B4CbdMT63rPXT2xzkQQlLMa2aGnv7GsrXXGDoMd4iFwfoW1sXmz68Ht+v0KEloW61hQhPvbhz1TsQo+AxI5kl9G+aS9a/ibUBcDN85qB+mNNdKD8vnCHqPh4="

# Only build master branch and tags of form 0.1 or 1.0.2 (all PRs will be built):
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

# Install various dependencies:
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install osxfuse; brew install python3 sshfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install sshfs; fi
  # Record some debugging info:
  - python --version
  - python2 --version
  - python3 --version
  # Decrypt the service key:
  - openssl aes-256-cbc -K $encrypted_6168b41c1bb0_key -iv $encrypted_6168b41c1bb0_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
  # Make sure gcloud is installed:
  - ./ci/setup-gcloud.sh
  # Make sure torsocks is installed:
  - ./ci/build-torsocks.sh

install:
  # Push Docker images to Google Container Registry; on OS X we don't bother, we
  # just hope that the parallel Linux job finished building and pushing first...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/push-images.sh; fi
  
script:
  - make virtualenv
  - export TELEPRESENCE_VERSION=$(make version)
  - export TELEPRESENCE_REGISTRY=gcr.io/${PROJECT_NAME}
  - export PATH=$HOME/google-cloud-sdk/bin:$PATH
  # Magic incantation to make kubectl work, because apparently gcloud can't do that correctly (see https://github.com/kubernetes/kubernetes/issues/30617)
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcloud-service-key.json
  - ./ci/test.sh

# If a commit is tagged, release the software:
deploy:
  provider: script
  skip_cleanup: true
  script: ci/release.sh
  on:
    tags: true
    branch: master
