---
kind: Service
apiVersion: v1
metadata:
  name: tp2
spec:
  selector:
    deployment: tp2
  ports:
  - name: tp2
    protocol: TCP
    port: 22
    targetPort: 8022
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tp2
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: tp2
  template:
    metadata:
      labels:
        deployment: tp2
    spec:
      containers:
      - name: proxy
        image: datawire/telepresence-k8s:0.75
        ports:
        - protocol: TCP
          containerPort: 8022
