[tool.towncrier]
    package = "telepresence"
    filename = "docs/reference/changelog.md"
    template = ".towncrier/template.md"
    directory = "newsfragments"
    start_string = "<!--- towncrier start line -->"
    title_format = "{version} ({project_date})"

    [[tool.towncrier.type]]
        directory = "misc"
	name = "Misc"
	showcontent = true
