apiVersion: v1
kind: Pod
metadata:
  name: telepresence
spec:
  containers:
  - name: telepresence
    image: datawire/remote-telepresence:dev
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
