# https://circleci.com/docs/2.0/

version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - "checkout"

      - run:
          name: "decrypt gcloud keys"
          command: |
            # To update:
            #   1) Generate a new key and IV:
            #      $ dd if=/dev/urandom count=64 bs=1 | md5sum
            #   2) Update GCLOUD_KEY and GCLOUD_IV in CircleCI "Environment
            #      Variables" configuration for Telepresence project.
            #   3) Encrypt the new gcloud key:
            #      $ ci/encrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV
            ci/decrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV

      - run:
          name: "setup non-Python environment"
          command: |
            ./environment-setup.sh datawireio telepresence-testing us-central1-a osx

      - run:
          name: "setup Python environment"
          command: |
            ./build --manage-virtualenv

      - run:
          name: "run lint checks"
          command: |
            ./build --flake8 --pylint --mypy

      - run:
          name: "run tests"
          command: |
            export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
            ./build --registry gcr.io/datawireio --build --version-suffix -osx --method inject-tcp --method vpn-tcp
