version: 2.1

executors:

  "vm-linux":
    machine:
      image: "ubuntu-2004:202008-01"

commands:

  "install-go":
    parameters:
      version:
        type: string
        default: "1.15"
    steps:
      - run:
          name: "Install Go << parameters.version >>"
          command: |
            set -x
            if [[ $OS == Windows_NT ]]; then
              curl https://dl.google.com/go/go<< parameters.version >>.windows-amd64.zip -o /tmp/go.zip
              mv /c/go /c/go-112
              unzip -q /tmp/go.zip -d /c/
            else
              curl https://dl.google.com/go/go<< parameters.version >>.$(uname -s | tr A-Z a-z)-amd64.tar.gz -o /tmp/go.tar.gz
              tar -C /tmp -xzf /tmp/go.tar.gz
              echo 'export PATH=/tmp/go/bin:$PATH' >> "$BASH_ENV"
              if [ -z "$(/tmp/go/bin/go env GOPROXY)" ]; then
                echo 'export GOPROXY=https://proxy.golang.org' >> "$BASH_ENV"
              fi
              . "$BASH_ENV"
            fi
            go version

  "install-kubectl":
    parameters:
      version:
        type: string
        default: "1.19.3"
    steps:
      - run:
          name: "Install kubectl << parameters.version >>"
          command: |
            curl -L --fail -o /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/v<< parameters.version >>/bin/$(uname -s | tr A-Z a-z)/amd64/kubectl
            sudo install /tmp/kubectl /usr/local/bin/kubectl

  "dirty-check":
    steps:
      - run:
          name: "Dirty check"
          command: |
            # On Windows, `git status` doesn't record no-op
            # line-ending changes in to the index, so things show as
            # dirty even if they aren't.  Trying to `add` them does
            # trigger the appropriate index update.  So do a `git add`
            # *before* the `git status --porcelain` to work around
            # Windows being terrible; we'd otherwise put the `git add`
            # inside of the `if` block to help generate better output
            # for `git diff`.
            git add .
            if [[ -n "$(git status --porcelain)" ]]; then
               PAGER= git diff --cached
               exit 1
            fi

  "save-logs":
    steps:
      - run:
          name: "Gather logs"
          when: always
          command: |
            rsync -ma --include='*/' --include='*.tap' --include='*.log' --include='Test*.webm' --exclude='*' . /tmp/test-logs
            if [ -s /tmp/telepresence.log ]; then
              cp /tmp/telepresence.log /tmp/test-logs
            fi
      - store_artifacts:
          name: "Store logs"
          path: /tmp/test-logs
          destination: test-logs

jobs:

  "build-and-test":
    executor: vm-linux
    steps:
      - checkout
      - install-go
      - run: make build
      - install-kubectl
      - run: make test
      - save-logs

  "lint":
    executor: vm-linux
    steps:
      - checkout
      # Split prep out to reduce noise in the output, and help with
      # timeouts.
      - run: make lint-deps
      - run:
          # Don't hold the Go compiler against golangci-lint's
          # timeout.
          name: "Pre-load Go build cache"
          command: go test -run=donotrun ./...
      - run: make lint

  "generate":
    executor: vm-linux
    steps:
      - checkout
      - run: make generate
      - dirty-check

workflows:

  'Dev':
    jobs:
      - build-and-test
      - lint
      - generate
