version: 2

jobs:

  macos-build:
    macos:
      xcode: "9.0"
    working_directory: ~/go/src/github.com/datawire/teleproxy
    steps:
      - run: |
          sudo pip install awscli

      # Golang install

      # For some reason it is faster to curl into a file than to just
      # pipe the curl straight to tar.
      - run: |
          sudo rm -rf /usr/local/go &&
          curl https://dl.google.com/go/go1.10.2.darwin-amd64.tar.gz -o /tmp/go.tgz &&
          sudo tar -C /usr/local -xzf /tmp/go.tgz

      # Golang paths
      - run: |
          echo 'export PATH=${PATH}:/usr/local/go/bin' >> ${BASH_ENV} &&
          echo 'export GOPATH=${HOME}/go' >> ${BASH_ENV}

      - run: 'echo PATH: ${PATH} || true'
      - run: 'echo GOPATH: ${GOPATH} || true'
      - run: go version

      - checkout
      - run: make test
      - run: make build
      - run: .circleci/deploy.sh

  machine-build:
    machine: true
    working_directory: ~/go/src/github.com/datawire/teleproxy
    steps:
      - run: |
          sudo pip install awscli

      # Golang install

      # For some reason it is faster to curl into a file than to just
      # pipe the curl straight to tar.
      - run: |
          sudo rm -rf /usr/local/go &&
          curl https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz -o /tmp/go.tgz &&
          sudo tar -C /usr/local -xzf /tmp/go.tgz

      # Golang paths
      - run: |
          echo 'export PATH=${PATH}:/usr/local/go/bin' >> ${BASH_ENV} &&
          echo 'export GOPATH=${HOME}/go' >> ${BASH_ENV}

      - run: 'echo PATH: ${PATH} || true'
      - run: 'echo GOPATH: ${GOPATH} || true'
      - run: go version

      - checkout
      - run: make test
      - run: make build
      - run: .circleci/deploy.sh

workflows:
  version: 2

  multibuild:
    jobs:
      - machine-build:
          filters:
            tags:
              only: /.*/
      - macos-build:
          filters:
            tags:
              only: /.*/
