# https://circleci.com/docs/2.0/

version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - run:
          name: "checkout"
          command: |
            set -e

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            mkdir -p ~/.ssh

            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
            ' >> ~/.ssh/known_hosts

            (umask 077; touch ~/.ssh/id_rsa)
            chmod 0600 ~/.ssh/id_rsa
            (cat <<EOF > ~/.ssh/id_rsa
            $CHECKOUT_KEY
            EOF
            )

            # use git+ssh instead of https
            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true

            if [ -e /Users/distiller/project/.git ]
            then
              cd /Users/distiller/project
              git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
            else
              mkdir -p /Users/distiller/project
              cd /Users/distiller/project
              # NOTE: Passing --unshallow here is the only change we've made
              # from the standard CircleCI checkout step.
              git clone --unshallow "$CIRCLE_REPOSITORY_URL" .
            fi

            if [ -n "$CIRCLE_TAG" ]
            then
              git fetch --force origin "refs/tags/${CIRCLE_TAG}"
            else
              git fetch --force origin "397.circleci-investigation:remotes/origin/397.circleci-investigation"
            fi


            if [ -n "$CIRCLE_TAG" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q "$CIRCLE_TAG"
            elif [ -n "$CIRCLE_BRANCH" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q -B "$CIRCLE_BRANCH"
            fi

            git reset --hard "$CIRCLE_SHA1"

      - run:
          name: "get git tags???"
          command: |
            git fetch --all --tags

      - run:
          name: "dump git tags"
          command: |
            git tag

      - run:
          name: "decrypt gcloud keys"
          command: |
            # To update:
            #   1) Generate a new key and IV:
            #      $ dd if=/dev/urandom count=64 bs=1 | md5sum
            #   2) Update GCLOUD_KEY and GCLOUD_IV in CircleCI "Environment
            #      Variables" configuration for Telepresence project.
            #   3) Encrypt the new gcloud key:
            #      $ ci/encrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV
            ci/decrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV

      - restore_cache:
          key: "system-components"

      - run:
          name: "setup non-Python environment"
          command: |
            # Note hard-coded OSX platform
            ./environment-setup.sh datawireio telepresence-testing us-central1-a osx

      - save_cache:
          key: "system-components"
          paths:
            - "~/Library/Caches/Homebrew"
            - "~/google-cloud-sdk/"

      - restore_cache:
          key: |
            requirements-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}-{{ checksum "k8s-proxy/requirements.txt" }}-{{ checksum "setup.py" }}

      - run:
          name: "setup Python environment"
          command: |
            export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
            ./build --registry gcr.io/datawireio --manage-virtualenv

      - save_cache:
          key: |
            requirements-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}-{{ checksum "k8s-proxy/requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            # OSX specific
            - "~/Library/Caches/pip/wheels/"

      - run:
          name: "run lint checks"
          command: |
            export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
            ./build --registry gcr.io/datawireio --flake8 --pylint --mypy

      - run:
          name: "run tests"
          command: |
            export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
            # Note hard-coded OSX version suffix.  We also skip container method due to the platform.
            ./build --circle
