---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telepresence-agent-injector
rules:
- apiGroups:
  - ""
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telepresence-agent-injector
subjects:
- kind: User
  name: system:serviceaccount:ambassador:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: telepresence-agent-injector
  apiGroup: rbac.authorization.k8s.io
