{{- if not .Values.rbac.only }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telepresence.fullname" . }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 2}}
  {{- end }}
  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
---
{{- if .Values.agentInjector.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentInjector.name }}
  namespace: {{ include "telepresence.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.agentInjector.service.ports }}
  ports:
  {{- toYaml . | nindent 2}}
  {{- end }}
  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
