name: "Run integration tests"
description: "Logic to run integration tests for all supported platforms"
inputs:
  kubeconfig:
    description: "The kubeconfig file to use for the test"
    required: true
runs:
  using: composite
  steps:
    - name: Run tests
      env:
        DTEST_KUBECONFIG: "${{ inputs.kubeconfig }}"
        DTEST_REGISTRY: "docker.io/datawire"
        SCOUT_DISABLE: "1"
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 60
        shell: bash
        command: |
          set -ex
          if [[ ${RUNNER_OS} == "Windows" ]]; then
            export PATH="$PATH:/C/Program Files/SSHFS-Win/bin"
          fi

          make check-integration
