on:
  push:
    branches:
      - master
      - build-wip

name: Test Telepresence

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      # Linting is only performed using go 1.15.x
      - name: Set up GolangCI-Lint
        if: ${{ matrix.go-version == '1.15.x' }}
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- latest

      - name: Lint
        if: ${{ matrix.go-version == '1.15.x' }}
        run: ./bin/golangci-lint run ./...
